#!/bin/sh

# Xcode Cloud runs this immediately after cloning the repository.
#
# The Debug and Release build configurations use IntelliNest-Info.xcconfig as
# their base configuration. That file holds real secrets and is git-ignored, so
# it is never present in a fresh Xcode Cloud checkout — without it the build
# fails with "Unable to open base configuration reference file".
#
# Local builds keep their own hand-maintained IntelliNest-Info.xcconfig. Here we
# recreate the same file from the environment variables defined on the Xcode
# Cloud workflow, so both paths feed identical keys into Info.plist.

set -eu

# ci_scripts/ runs with the repo root one level up. CI_PRIMARY_REPOSITORY_PATH
# is set by Xcode Cloud; fall back to the parent dir for safety.
REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
XCCONFIG_PATH="$REPO_ROOT/IntelliNest-Info.xcconfig"

# The canonical secret keys, matching Github-Info.xcconfig. Anything not provided
# as an environment variable is written as empty so the xcconfig is always
# complete. Keep this list in sync with Github-Info.xcconfig.
KEYS="
EXTERNAL_URL
LOCAL_SSID
SECRET_HASS_TOKEN
SECRET_HASS_TOKEN_SARAH
SECRET_YALE_API_KEY
SECRET_YALE_API_URL
SPOTIFY_CLIENT_ID
"

{
    echo "// Generated by ci_scripts/ci_post_clone.sh for Xcode Cloud."
    echo "// Do not commit — values come from the Xcode Cloud workflow environment."
    for key in $KEYS; do
        # Indirect expansion, POSIX sh style: read the env var named by $key.
        value=$(eval "printf '%s' \"\${$key:-}\"")
        echo "$key = $value"
    done
} > "$XCCONFIG_PATH"

echo "Wrote $XCCONFIG_PATH with ${CI_XCODE_SCHEME:-build} secrets from the workflow environment."
